Repository AI-iLearning/AI-Learning, pull requests merged in 2024-09, with the labels that each got.

#75 [Fix/#74/city list] city 수정에 따른 수정사항 반영
  frontend/src/api/calendar/getAllPlace.ts
  frontend/src/api/calendar/getTimelineAll.ts
  frontend/src/api/calendar/postTimelineDay.ts
  frontend/src/api/schedule/getSchedule.ts
  frontend/src/api/schedule/postEdit.ts
  frontend/src/pages/AISchedule3Page/AISchedule3.tsx
  frontend/src/pages/AISchedule3Page/components/ScheduleItem.tsx
  frontend/src/pages/CalendarPage/components/PlaceBox.tsx
  frontend/src/pages/CalendarPage/components/PlaceBoxItem.tsx
  frontend/src/pages/PlaceDetailPage/PlaceDetail.tsx
  frontend/src/style/CityColor.ts
  frontend/src/style/CityMapper.ts
Labels: fix

#81 Feature/#80/kakao login
  frontend/public/img/kakao_login_medium_wide.png
  frontend/public/index.html
  frontend/src/api/auth/postKakaoCallback.ts
  frontend/src/api/auth/postNewAccessToken.ts
  frontend/src/api/auth/postRefreshAccessToken.ts
  frontend/src/api/auth/postRegister.ts
  frontend/src/api/axiosInstance.ts
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/LoginPage/components/KakaoRedirectHandle.tsx
  frontend/src/pages/LoginPage/components/LoginForm.tsx
  frontend/src/pages/LoginPage/components/SocialLogin.tsx
  frontend/src/pages/LoginPage/styles/Login.style.tsx
  frontend/src/pages/ProfilePage/components/LogoutButton.tsx
  frontend/src/pages/RegisterPage/Register.tsx
  frontend/src/pages/RegisterPage/components/RegisterForm.tsx
  frontend/src/router.tsx
  frontend/src/stores/authToken.ts
  frontend/src/utils/isAxios401Error.ts
Labels: Feat, Test

#82 [Fix ✏️] 링크 수정
  frontend/src/pages/LoginPage/components/SocialLogin.tsx
Labels: fix

#83 [Fix ✏️] 카카오 이메일 정보 받아서 회원가입 페이지 적용
  frontend/src/pages/LoginPage/components/KakaoRedirectHandle.tsx
  frontend/src/pages/LoginPage/components/SocialLogin.tsx
  frontend/src/pages/RegisterPage/components/RegisterForm.tsx
Labels: fix

#89 [Feat💡] 장소 추천(지도) + 장소 추천 세부페이지 구축
  frontend/public/img/placeRecommend/Background.png
  frontend/public/img/placeRecommend/Busan.png
  frontend/public/img/placeRecommend/Chungcheongdo.png
  frontend/public/img/placeRecommend/Gangwondo.png
  frontend/public/img/placeRecommend/Gwangju.png
  frontend/public/img/placeRecommend/Gyeonggido.png
  frontend/public/img/placeRecommend/Gyeongju.png
  frontend/public/img/placeRecommend/Gyeongsangdo.png
  frontend/public/img/placeRecommend/Incheon.png
  frontend/public/img/placeRecommend/Jeju.png
  frontend/public/img/placeRecommend/Jeonlado.png
  frontend/public/img/placeRecommend/Korea.png
  frontend/public/img/placeRecommend/Korea2.png
  frontend/public/img/placeRecommend/Seoul.png
  frontend/src/api/recommend/postRecommendPlace.ts
  frontend/src/pages/DateSelectedPage/DateSelected.tsx
  frontend/src/pages/RecommendPage/Recommend.tsx
  frontend/src/pages/RecommendPage/RecommendDetail.tsx
  frontend/src/pages/RecommendPage/components/PlaceItem.tsx
  frontend/src/pages/RecommendPage/img/dummy.png
  frontend/src/pages/RecommendPage/styles/Recommend.style.tsx
  frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
  frontend/src/router.tsx
Labels: Feat, Design

#91 [Feat 💡] 캘린더 내 장소추가 기능 구현
  frontend/src/api/place/postAddPlace.ts
  frontend/src/pages/DateSelectedPage/DateSelected.tsx
  frontend/src/pages/DateSelectedPage/components/MainCalendar.tsx
  frontend/src/pages/DateSelectedPage/components/PlaceAddBanner.tsx
  frontend/src/pages/DateSelectedPage/styles/DateSelected.style.tsx
  frontend/src/pages/DateSelectedPage/styles/MainCalendar.style.tsx
  frontend/src/pages/DateSelectedPage/styles/PlaceAddBanner.style.tsx
Labels: Feat, Design

#93 [Test 💻] 카카오 로그인 로직 수정
  frontend/src/api/auth/postKakaoCallback.ts
  frontend/src/api/auth/postNewAccessToken.ts
  frontend/src/pages/LoginPage/components/KakaoRedirectHandle.tsx
  frontend/src/pages/LoginPage/components/LoginForm.tsx
  frontend/src/stores/authKakaoToken.ts
  frontend/src/stores/authToken.ts
Labels: fix, Test

#94 [Feat 💡] 챗봇과 사용자 1:1 채팅 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/PlaceDetailPage/PlaceDetail.tsx
  frontend/src/pages/PlaceDetailPage/components/ChatDrawer/ChatDrawer.tsx
  frontend/src/pages/PlaceDetailPage/components/ChatDrawer/ChatInput.tsx
  frontend/src/pages/PlaceDetailPage/components/ChatDrawer/ChatMessages.tsx
  frontend/src/pages/PlaceDetailPage/components/ChatDrawer/DrawerButton.tsx
  frontend/src/pages/PlaceDetailPage/styles/ChatDrawer.style.tsx
  frontend/src/pages/PlaceDetailPage/styles/DrawerButton.style.tsx
  frontend/src/pages/PlaceDetailPage/styles/PlaceDetail.style.tsx
  frontend/src/stores/useChatStore.ts
Labels: Feat, Design, Test

#99 [Fix ✏️] 주소 오류 해결
  frontend/src/pages/PlaceDetailPage/components/MiddleMenuBar.tsx
Labels: fix

#100 [Feat 💡] 화면 세로 모드 고정
  frontend/src/App.tsx
  frontend/src/global.d.ts
Labels: Feat

#101 [Feat 💡] 세로 모드 고정
  frontend/src/App.tsx
  frontend/src/global.d.ts
Labels: fix

#102 [Fix ✏️] 화면 세로 모드 고정
  frontend/src/App.tsx
  frontend/src/style/MobileStyle.ts
Labels: fix

#103 [Fix ✏️] 세로 모드 고정 수정
  frontend/src/style/MobileStyle.ts
Labels: fix

#104 [Feature/#30/profile] 프로필 페이지 기능 구현
  frontend/public/img/level/chosun.png
  frontend/public/img/level/goryeo.png
  frontend/public/img/level/modern.png
  frontend/public/img/level/prehistoric.png
  frontend/public/img/level/threeKingdoms.png
  frontend/src/api/auth/getMyInfo.ts
  frontend/src/api/profile/getRecentPlace.ts
  frontend/src/components/InfoBanner/InfoBanner.tsx
  frontend/src/components/InfoBanner/styles/InfoBanner.style.tsx
  frontend/src/pages/MyInfoEditPage/MyInfoEdit.tsx
  frontend/src/pages/MyInfoEditPage/styles/MyInfoEdit.style.tsx
  frontend/src/pages/ProfilePage/Profile.tsx
  frontend/src/pages/ProfilePage/components/LogoutButton.tsx
  frontend/src/pages/ProfilePage/components/MyLevel.tsx
  frontend/src/pages/ProfilePage/components/PlaceItem.tsx
  frontend/src/pages/ProfilePage/components/PlaceList.tsx
  frontend/src/pages/ProfilePage/components/ProfileSection.tsx
  frontend/src/pages/ProfilePage/styles/MyLevel.style.tsx
  frontend/src/pages/ProfilePage/styles/PlaceList.style.tsx
  frontend/src/pages/ProfilePage/styles/Profile.style.tsx
  frontend/src/router.tsx
Labels: Feat, Design

#110 Fix/#109/recommend all
  frontend/public/img/default_pic.png
  frontend/src/App.tsx
  frontend/src/api/axiosInstance.ts
  frontend/src/api/calendar/getAllPlace.ts
  frontend/src/api/recommend/postRecommendPlace.ts
  frontend/src/components/Loading/Loading.tsx
  frontend/src/components/Loading/styles/Loading.style.tsx
  frontend/src/hooks/useAllPlace.ts
  frontend/src/pages/AISchedule2Page/AISchedule2.tsx
  frontend/src/pages/CalendarPage/components/AddPlace.tsx
  frontend/src/pages/CalendarPage/styles/AddPlace.style.tsx
  frontend/src/pages/RecommendPage/RecommendDetail.tsx
  frontend/src/pages/RecommendPage/components/PlaceItem.tsx
  frontend/src/pages/RecommendPage/img/dummy.png
  frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
Labels: fix, Feat, Design, Test

#113 [Feature/#95/my info] 내 정보 수정 기능 1차
  frontend/src/api/auth/deleteRemove.ts
  frontend/src/api/auth/postCheckInfo.ts
  frontend/src/api/auth/postResetPassword.ts
  frontend/src/api/place/postIndoor.ts
  frontend/src/api/profile/postCheckPassword.ts
  frontend/src/api/profile/postNewPassword.ts
  frontend/src/api/profile/postUserUpdate.ts
  frontend/src/pages/ChangeInfoPage/BackButton/BackButton.tsx
  frontend/src/pages/ChangeInfoPage/BackButton/styles/BackButton.style.tsx
  frontend/src/pages/ChangeInfoPage/ChangeInfo.tsx
  frontend/src/pages/ChangeInfoPage/styles/ChangeInfo.style.tsx
  frontend/src/pages/ChangeNicknamePage/BackButton/BackButton.tsx
  frontend/src/pages/ChangeNicknamePage/BackButton/styles/BackButton.style.tsx
  frontend/src/pages/ChangeNicknamePage/ChangeNickname.tsx
  frontend/src/pages/ChangeNicknamePage/styles/ChangeNickname.style.tsx
  frontend/src/pages/ChangePasswordPage/BackButton/BackButton.tsx
  frontend/src/pages/ChangePasswordPage/BackButton/styles/BackButton.style.tsx
  frontend/src/pages/ChangePasswordPage/ChangePassword.tsx
  frontend/src/pages/ChangePasswordPage/styles/ChangePassword.style.tsx
  frontend/src/pages/CheckPasswordPage/BackButton/BackButton.tsx
  frontend/src/pages/CheckPasswordPage/BackButton/styles/BackButton.style.tsx
  frontend/src/pages/CheckPasswordPage/CheckPassword.tsx
  frontend/src/pages/CheckPasswordPage/styles/CheckPassword.style.tsx
  frontend/src/pages/MyInfoEditPage/MyInfoEdit.tsx
  frontend/src/pages/MyInfoEditPage/components/BackButton/BackButton.tsx
  frontend/src/pages/MyInfoEditPage/components/BackButton/styles/BackButton.style.tsx
  frontend/src/pages/MyInfoEditPage/components/ListItem.tsx
  frontend/src/pages/MyInfoEditPage/styles/MyInfoEdit.style.tsx
  frontend/src/pages/ProfilePage/components/ProfileSection.tsx
  frontend/src/router.tsx
Labels: Feat, Design, Test

#116 [Feature/#36/date drawer] Drawer와 캘린더 기능 구현 및 수정
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/CalendarPage/components/DateDrawer.tsx
  frontend/src/pages/CalendarPage/components/MainCalendar.tsx
  frontend/src/pages/CalendarPage/components/PlaceBox.tsx
  frontend/src/pages/CalendarPage/components/PlaceBoxItem.tsx
  frontend/src/pages/CalendarPage/styles/Calendar.style.tsx
Labels: fix, Feat

#112 [Feat💡] EachLevel Page 구축
  frontend/src/api/profile/postLevel.ts
  frontend/src/pages/ProfilePage/components/EachLevel.tsx
  frontend/src/pages/ProfilePage/components/LevelItem.tsx
  frontend/src/pages/ProfilePage/components/MyLevel.tsx
  frontend/src/pages/ProfilePage/styles/EachLevel.style.tsx
  frontend/src/pages/ProfilePage/styles/LevelItem.style.tsx
  frontend/src/router.tsx
Labels: Feat, Design

#122 [Design 🎨] css 수정
  frontend/src/pages/RankPage/Rank.tsx
  frontend/src/pages/RankPage/img/1.png
  frontend/src/pages/RankPage/img/10.png
  frontend/src/pages/RankPage/img/11.png
  frontend/src/pages/RankPage/img/12.png
  frontend/src/pages/RankPage/img/13.png
  frontend/src/pages/RankPage/img/14.png
  frontend/src/pages/RankPage/img/15.png
  frontend/src/pages/RankPage/img/16.png
  frontend/src/pages/RankPage/img/17.png
  frontend/src/pages/RankPage/img/18.png
  frontend/src/pages/RankPage/img/19.png
  frontend/src/pages/RankPage/img/2.png
  frontend/src/pages/RankPage/img/20.png
  frontend/src/pages/RankPage/img/21.png
  frontend/src/pages/RankPage/img/22.png
  frontend/src/pages/RankPage/img/23.png
  frontend/src/pages/RankPage/img/24.png
  frontend/src/pages/RankPage/img/25.png
  frontend/src/pages/RankPage/img/26.png
  frontend/src/pages/RankPage/img/27.png
  frontend/src/pages/RankPage/img/28.png
  frontend/src/pages/RankPage/img/29.png
  frontend/src/pages/RankPage/img/3.png
  frontend/src/pages/RankPage/img/30.png
  frontend/src/pages/RankPage/img/31.png
  frontend/src/pages/RankPage/img/32.png
  frontend/src/pages/RankPage/img/4.png
  frontend/src/pages/RankPage/img/5.png
  frontend/src/pages/RankPage/img/6.png
  frontend/src/pages/RankPage/img/7.png
  frontend/src/pages/RankPage/img/8.png
  frontend/src/pages/RankPage/img/9.png
  frontend/src/pages/RankPage/styles/Rank.style.tsx
Labels: fix, Design

#124 [Fix ✏️] 장소추가 후 캘린더 돌아올 때 해당 날짜 Drawer 열리도록 수정
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/CalendarPage/components/AddPlace.tsx
  frontend/src/pages/CalendarPage/components/MainCalendar.tsx
  frontend/src/pages/DateSelectedPage/components/PlaceAddBanner.tsx
  frontend/src/pages/DateSelectedPage/styles/PlaceAddBanner.style.tsx
Labels: fix

#130 [Feat💡] 실내 장소 추천 UI 구축
  frontend/src/pages/IndoorPlacePage/IndoorPlace.tsx
  frontend/src/pages/IndoorPlacePage/components/IndoorPlaceItem.tsx
  frontend/src/pages/IndoorPlacePage/styles/IndoorPlace.style.tsx
  frontend/src/pages/IndoorPlacePage/styles/IndoorPlaceItem.style.tsx
  frontend/src/router.tsx
Labels: Feat, Design

#131 [Fix✏️] Indoor API 로직 수정
  frontend/src/api/place/postIndoor.ts
  frontend/src/pages/IndoorPlacePage/IndoorPlace.tsx
  frontend/src/pages/ProfilePage/components/ProfileSection.tsx
Labels: fix

#119 [Feat💡] AI 일정(3) Delete 기능 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/AISchedule1Page/AISchedule1.tsx
  frontend/src/pages/AISchedule2Page/AISchedule2.tsx
  frontend/src/pages/AISchedule3Page/AISchedule3.tsx
  frontend/src/pages/AISchedule3Page/components/Schedule.tsx
  frontend/src/pages/AISchedule3Page/components/ScheduleItem.tsx
  frontend/src/pages/AISchedule3Page/styles/AISchedule3.style.tsx
Labels: fix, Feat, Design

#133 Feature/#127/detail
  frontend/public/index.html
  frontend/src/hooks/useLockBodyScroll.tsx
  frontend/src/pages/PlaceDetailPage/PlaceDetail.tsx
  frontend/src/pages/PlaceDetailPage/components/AccomodationList.tsx
  frontend/src/pages/PlaceDetailPage/components/ContentType/ContentType12.tsx
  frontend/src/pages/PlaceDetailPage/components/ContentType/ContentType14.tsx
  frontend/src/pages/PlaceDetailPage/components/ContentType/ContentType15.tsx
  frontend/src/pages/PlaceDetailPage/components/PlaceItem.tsx
  frontend/src/pages/PlaceDetailPage/components/RestaurantList.tsx
  frontend/src/pages/PlaceDetailPage/styles/AccomodationItem.style.tsx
Labels: Feat, Design, Refactor

#134 [Feat 💡] chatgpt api 활용해 교외체험학습계획 결과 넣어주기
  frontend/src/pages/PlaceDetailPage/PlaceDetail.tsx
  frontend/src/pages/PlaceDetailPage/components/StudyPlan/ChatGPT.ts
  frontend/src/pages/PlaceDetailPage/components/StudyPlan/StudyPlan.tsx
Labels: Feat

#135 Fix/#121/rank
  frontend/src/pages/RankPage/styles/Rank.style.tsx
Labels: Design

#136 [Fix/#97/chat] 채팅 컴포넌트 이슈 해결
  frontend/src/pages/PlaceDetailPage/PlaceDetail.tsx
  frontend/src/pages/PlaceDetailPage/components/ChatDrawer/ChatDrawer.tsx
  frontend/src/pages/PlaceDetailPage/components/ChatDrawer/ChatInput.tsx
  frontend/src/pages/PlaceDetailPage/components/ChatDrawer/ChatMessages.tsx
  frontend/src/pages/PlaceDetailPage/components/StudyPlan/ChatGPT.ts
  frontend/src/pages/PlaceDetailPage/components/StudyPlan/StudyPlan.tsx
  frontend/src/pages/PlaceDetailPage/styles/ChatDrawer.style.tsx
Labels: fix, Feat, Design

#138 [Design 🎨] 레벨바 커스튬 수정
  frontend/src/pages/PlaceDetailPage/PlaceDetail.tsx
  frontend/src/pages/ProfilePage/styles/MyLevel.style.tsx
Labels: fix, Design

#141 [Feature/#95/my info] 내 정보 수정 기능 완료 및 회원정보 수정
  frontend/src/api/auth/getMyInfo.ts
  frontend/src/api/auth/postRegister.ts
  frontend/src/api/profile/postUserUpdate.ts
  frontend/src/datas/EditCityMapper.ts
  frontend/src/datas/RegisterCityMapper.ts
  frontend/src/pages/ChangeInfoPage/ChangeInfo.tsx
  frontend/src/pages/ChangeInfoPage/styles/ChangeInfo.style.tsx
  frontend/src/pages/ChangeNicknamePage/ChangeNickname.tsx
  frontend/src/pages/LoginPage/styles/Login.style.tsx
  frontend/src/pages/MyInfoEditPage/MyInfoEdit.tsx
  frontend/src/pages/MyInfoEditPage/components/CloseButton/CloseButton.tsx
  frontend/src/pages/MyInfoEditPage/components/CloseButton/styles/CloseButton.style.tsx
  frontend/src/pages/MyInfoEditPage/components/ProfileDrawer.tsx
  frontend/src/pages/MyInfoEditPage/styles/ProfileDrawer.style.tsx
  frontend/src/pages/RegisterPage/components/RegisterForm.tsx
  frontend/src/pages/RegisterPage/styles/Register.style.tsx
  frontend/src/style/CityMapper2.ts
Labels: fix, Feat, Design

#142 Feature/#126/guide
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/BottomMenuBar/BottomMenuBar.tsx
  frontend/src/pages/AISchedule1Page/AISchedule1.tsx
  frontend/src/pages/CalendarPage/components/DrawerButton.tsx
  frontend/src/pages/CalendarPage/styles/DrawerButton.style.tsx
  frontend/src/pages/GuidePage/Guide.tsx
  frontend/src/pages/GuidePage/styles/Guide.style.tsx
  frontend/src/pages/PlaceDetailPage/PlaceDetail.tsx
  frontend/src/pages/PlaceDetailPage/components/ChatDrawer/DrawerButton.tsx
  frontend/src/pages/PlaceDetailPage/styles/DrawerButton.style.tsx
  frontend/src/router.tsx
Labels: Feat, Refactor

#151 [Fix✏️] AISchedule1 관련 수정 사항
  frontend/src/components/InfoBannerNoX/InfoBannerNoX.tsx
  frontend/src/components/InfoBannerNoX/styles/InfoBannerNoX.style.tsx
  frontend/src/pages/AISchedule1Page/AISchedule1.tsx
  frontend/src/pages/AISchedule1Page/styles/AISchedule1.style.tsx
  frontend/src/pages/AISchedule1Page/styles/BackButton.style.tsx
  frontend/src/pages/CalendarInputPage/CalenderCycle.tsx
Labels: fix, Design

#152 [Design🎨] AI스케줄 (3)
  frontend/src/pages/AISchedule3Page/AISchedule3.tsx
  frontend/src/pages/AISchedule3Page/components/ScheduleItem.tsx
  frontend/src/pages/AISchedule3Page/styles/AISchedule3.style.tsx
Labels: Design

#153 [Feat 💡] 가이드 목록 구현
  frontend/src/api/guide/postMessage.ts
  frontend/src/api/guide/postSend.ts
  frontend/src/api/profile/getPattern.ts
  frontend/src/pages/GuidePage/Guide.tsx
  frontend/src/pages/GuidePage/components/GuideBox.tsx
  frontend/src/pages/GuidePage/components/GuideBoxItem.tsx
  frontend/src/pages/GuidePage/datas/GuideList.ts
  frontend/src/pages/GuidePage/styles/Guide.style.tsx
  frontend/src/pages/GuidePage/styles/GuideBox.style.tsx
Labels: Feat, Design, Test

#154 [Design🎨] 순위UI
  frontend/src/pages/RankPage/Rank.tsx
  frontend/src/pages/RankPage/styles/Rank.style.tsx
Labels: Design

#156 [Design🎨] 추천장소 Fix
  frontend/src/pages/CalendarPage/styles/AddPlace.style.tsx
Labels: Design

#159 [Fix✏️] EachLevel(레벨별) Fix
  frontend/src/pages/ProfilePage/components/EachLevel.tsx
  frontend/src/pages/ProfilePage/styles/EachLevel.style.tsx
Labels: fix, Feat, Design

#161 [Design🎨] 알림(Alert) 중앙 정렬
  frontend/src/pages/AlertPage/styles/Alert.style.tsx
Labels: Design

#150 [Feat💡] 아이디/ 비밀번호 틀렸을 시 로직 구성
  frontend/src/pages/LoginPage/components/LoginForm.tsx
Labels: fix

#163 [Feat💡] AI 버튼 zustand 초기화 기능
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/stores/useScheduleStore.ts
Labels: fix, Feat

#164 [Fix/#158/detail] 상세 장소 페이지 이슈 해결
  frontend/src/pages/CalendarPage/components/AddPlace.tsx
  frontend/src/pages/CalendarPage/components/PlaceBoxItem.tsx
  frontend/src/pages/IndoorPlacePage/IndoorPlace.tsx
  frontend/src/pages/PlaceDetailPage/PlaceDetail.tsx
  frontend/src/pages/PlaceDetailPage/styles/AccomodationItem.style.tsx
  frontend/src/pages/PlaceDetailPage/styles/PlaceDetail.style.tsx
  frontend/src/pages/ProfilePage/components/EachLevel.tsx
  frontend/src/pages/ProfilePage/components/PlaceList.tsx
  frontend/src/pages/RankPage/Rank.tsx
  frontend/src/pages/RecommendPage/RecommendDetail.tsx
Labels: fix, Design

#167 [Fix✏️] 날씨 팝업 수정
  frontend/src/api/profile/postAlertDelete.ts
  frontend/src/components/AlertPopUp/IndoorAlertPopUp/styles/IndoorAlertPopUp.style.tsx
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/IndoorPlacePage/IndoorPlace.tsx
  frontend/src/pages/IndoorPlacePage/styles/IndoorPlaceItem.style.tsx
Labels: fix, Design, Refactor
