Repository AI-iLearning/AI-Learning, pull requests merged in 2024-10, with the labels that each got.

#168 [Design🎨] rank 위치 수정 및 Margin 추가
  frontend/src/pages/CalendarPage/styles/AddPlace.style.tsx
  frontend/src/pages/RankPage/Rank.tsx
  frontend/src/pages/RankPage/styles/Rank.style.tsx
  frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
Labels: fix, Design

#169 [Feat💡] 비밀번호 재설정 페이지 구축
  frontend/src/pages/LoginPage/components/CreateAccount.tsx
  frontend/src/pages/PasswordChangePage/PasswordChange1.tsx
  frontend/src/pages/PasswordChangePage/PasswordChange3.tsx
  frontend/src/pages/PasswordChangePage/components/PasswordChangeForm.tsx
  frontend/src/pages/PasswordChangePage/components/PasswordChangeForm3.tsx
  frontend/src/pages/PasswordChangePage/components/XButton.tsx
  frontend/src/pages/PasswordChangePage/styles/PasswordChange.style.tsx
  frontend/src/pages/RankPage/Rank.tsx
  frontend/src/router.tsx
Labels: Feat, Design

#171 [Fix/#144/register] 회원가입 로직 수정
  frontend/src/pages/RegisterPage/components/RegisterForm.tsx
  frontend/src/pages/RegisterPage/styles/Register.style.tsx
Labels: fix

#173 [Fix ✏️] year 안 바뀌는 문제 해결
  frontend/src/pages/ChangeInfoPage/ChangeInfo.tsx
Labels: fix

#175 [Fix/#145/date drawer] 캘린더 Drawer 관련 이슈 해결
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/CalendarPage/components/PlaceBoxItem.tsx
  frontend/src/pages/CalendarPage/components/TodayMemo.tsx
  frontend/src/pages/CalendarPage/styles/Calendar.style.tsx
  frontend/src/pages/CalendarPage/styles/PlaceBox.style.tsx
  frontend/src/pages/CalendarPage/styles/TodayMemo.style.tsx
Labels: fix, Design

#176 [Feat 💡] 오늘의 메모 로직 수정
  frontend/src/pages/CalendarPage/Calendar.tsx
Labels: fix

#178 [Design 🎨] 문구 및 색상 수정
  frontend/src/pages/AISchedule3Page/AISchedule3.tsx
  frontend/src/pages/AISchedule3Page/styles/AISchedule3.style.tsx
Labels: Design

#170 [Fix✏️] 순위 page 잘림 이슈 해결
  frontend/src/pages/RankPage/styles/Rank.style.tsx
Labels: Design

#179 [Feature/#126/guide] 가이드 메뉴 구현 완료
  frontend/src/pages/GuidePage/Guide.tsx
  frontend/src/pages/GuidePage/components/BackButton/BackButton.tsx
  frontend/src/pages/GuidePage/components/ChatGuideList.tsx
  frontend/src/pages/GuidePage/components/ChatRoom.tsx
  frontend/src/pages/GuidePage/components/GuideBoxItem.tsx
  frontend/src/pages/GuidePage/datas/GuideList.ts
  frontend/src/pages/GuidePage/styles/BackButton.style.tsx
  frontend/src/pages/GuidePage/styles/ChatRoom.style.tsx
  frontend/src/pages/GuidePage/styles/Guide.style.tsx
  frontend/src/pages/GuidePage/styles/GuideBox.style.tsx
  frontend/src/router.tsx
Labels: Feat, Design

#181 [Fix✏️] ios 하단바 문제 해결
  frontend/src/App.tsx
  frontend/src/components/BottomMenuBar/styles/BottomMenuBar.style.tsx
  frontend/src/style/GlobalStyle.ts
Labels: fix, Design

#182 [Fix✏️] 원상복구
  frontend/src/App.tsx
  frontend/src/components/BottomMenuBar/styles/BottomMenuBar.style.tsx
  frontend/src/style/GlobalStyle.ts
Labels: fix

#183 [Fix✏️] 배열 길이 0 예외처리
  frontend/src/pages/AlertPage/Alert.tsx
  frontend/src/pages/IndoorPlacePage/IndoorPlace.tsx
Labels: fix

#185 [Fix✏️] 백버튼 관련 사항, 하단 버튼 크기 조정
  frontend/src/pages/AISchedule1Page/components/BackButton/BackButton.tsx
  frontend/src/pages/AISchedule2Page/AISchedule2.tsx
  frontend/src/pages/AISchedule2Page/styles/AISchedule2.style.tsx
Labels: fix, Design

#187 [Test 💻] 가이드 채팅 목록 반환 수정
  frontend/src/api/guide/getSelect.ts
  frontend/src/pages/GuidePage/components/ChatGuideList.tsx
Labels: fix, Test

#188 [Remove 🗑️] BackButton 및 콘솔 삭제
  frontend/src/pages/AISchedule3Page/AISchedule3.tsx
  frontend/src/pages/AISchedule3Page/styles/AISchedule3.style.tsx
Labels: fix

#189 [Design 🎨] 404 페이지 구현
  frontend/src/pages/NotFoundPage/NotFound.tsx
  frontend/src/pages/NotFoundPage/styles/NotFound.style.tsx
  frontend/src/router.tsx
Labels: Design

#190 [Design 🎨] 순위 -> 러닝픽 수정
  frontend/src/components/BottomMenuBar/BottomMenuBar.tsx
Labels: Design

#191 [Remove 🗑️] 콘솔 제거
  frontend/src/pages/AISchedule1Page/AISchedule1.tsx
  frontend/src/pages/AISchedule2Page/AISchedule2.tsx
  frontend/src/pages/AISchedule3Page/AISchedule3.tsx
  frontend/src/pages/AlertPage/Alert.tsx
  frontend/src/pages/CalendarInputPage/CalendarInput.tsx
  frontend/src/pages/CalendarInputPage/CalenderCycle.tsx
  frontend/src/pages/CalendarInputPage/components/CalenderFrame2.tsx
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/CalendarPage/components/AddPlace.tsx
  frontend/src/pages/CalendarPage/components/DateDrawer.tsx
  frontend/src/pages/CalendarPage/components/NoPlace.tsx
  frontend/src/pages/CalendarPage/components/NoPlace2.tsx
  frontend/src/pages/CalendarPage/components/PlaceBox.tsx
  frontend/src/pages/ChangeInfoPage/ChangeInfo.tsx
  frontend/src/pages/GuidePage/Guide.tsx
  frontend/src/pages/IndoorPlacePage/IndoorPlace.tsx
  frontend/src/pages/LoginPage/Login.tsx
  frontend/src/pages/LoginPage/components/KakaoRedirectHandle.tsx
  frontend/src/pages/LoginPage/components/LoginForm.tsx
  frontend/src/pages/PasswordChangePage/PasswordChange1.tsx
  frontend/src/pages/PasswordChangePage/PasswordChange3.tsx
  frontend/src/pages/PasswordChangePage/components/PasswordChangeForm.tsx
  frontend/src/pages/PasswordChangePage/components/PasswordChangeForm3.tsx
  frontend/src/pages/PlaceDetailPage/components/MiddleMenuBar.tsx
  frontend/src/pages/PlaceDetailPage/components/PlaceItem.tsx
  frontend/src/pages/ProfilePage/Profile.tsx
  frontend/src/pages/ProfilePage/components/EachLevel.tsx
  frontend/src/pages/ProfilePage/components/LevelItem.tsx
  frontend/src/pages/ProfilePage/components/Pattern.tsx
  frontend/src/pages/ProfilePage/components/ProfileSection.tsx
  frontend/src/pages/RankPage/Rank.tsx
  frontend/src/pages/RegisterPage/components/RegisterForm.tsx
Labels: fix

#192 [Fix ✏️] 공유하기 링크 열 때 발생하는 오류 해결
  frontend/src/components/BackButton/BackButton.tsx
  frontend/src/pages/DateSelectedPage/components/PlaceAddBanner.tsx
  frontend/src/pages/PlaceDetailPage/PlaceDetail.tsx
Labels: fix

#193 [Design 🎨] 채팅창 아이폰 아래 영역 고려
  frontend/src/pages/GuidePage/styles/ChatRoom.style.tsx
  frontend/src/pages/PlaceDetailPage/styles/ChatDrawer.style.tsx
Labels: Design

#194 [Fix ✏️] Drawer 이벤트 발생 시 뒷페이지 영역 스크롤 방지(고정)
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/CalendarPage/components/MainCalendar.tsx
Labels: fix

#196 [💡Feat] 타이머 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/TimerLoading/TimerLoading.tsx
  frontend/src/components/TimerLoading/styles/TimerLoading.style.tsx
  frontend/src/pages/AISchedule2Page/AISchedule2.tsx
Labels: Feat, Design

#198 [Fix✏️] 폰트 깨짐 이슈 해결
  frontend/src/style/font.css
Labels: fix
