Repository AI-iLearning/AI-Learning, pull requests merged in 2024-07, with the labels that each got.

#6 Design/#5/setting
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/style/GlobalStyle.ts
  frontend/src/style/font.css
  frontend/src/utils/mobileScreenSize/setScreenHeight.ts
Labels: Design

#7 [Chore 🚀] Prettier 규칙 재설정 및 모바일 화면 비율 재설정
  frontend/.eslintrc.cjs
  frontend/prettierrc.json
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/reportWebVitals.ts
  frontend/src/setupTests.ts
  frontend/src/style/GlobalStyle.ts
  frontend/src/style/font.css
  frontend/src/utils/mobileScreenSize/setScreenHeight.ts
Labels: fix, Design, Refactor

#19 Refactor/#18/zustand
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/BottomMenuBar/BottomMenuBar.tsx
  frontend/src/index.tsx
  frontend/src/pages/LoginPage/Login.tsx
  frontend/src/pages/ProfilePage/Profile.tsx
  frontend/src/pages/RankPage/Rank.tsx
  frontend/src/pages/RecommendPage/Recommend.tsx
  frontend/src/pages/TestPage/Test.tsx
  frontend/src/router.tsx
  frontend/src/stores/useBottomMenuStore.ts
Labels: fix, Refactor

#20 Feature/#1/login
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/auth/postLogin.ts
  frontend/src/api/axiosInstance.ts
  frontend/src/pages/LoginPage/Login.tsx
  frontend/src/pages/LoginPage/components/CreateAccount.tsx
  frontend/src/pages/LoginPage/components/LoginForm.tsx
  frontend/src/pages/LoginPage/styles/Login.style.tsx
  frontend/src/pages/RegisterPage/Register.tsx
  frontend/src/router.tsx
Labels: Feat, Design

#21 [Feat 💡] 회원가입 기능 1차
  frontend/src/api/auth/postCheckEmail.ts
  frontend/src/api/auth/postCheckNickname.ts
  frontend/src/api/auth/postRegister.ts
  frontend/src/components/BottomButton/styles/BottomButton.style.tsx
  frontend/src/pages/RegisterPage/Register.tsx
  frontend/src/pages/RegisterPage/components/RegisterForm.tsx
  frontend/src/pages/RegisterPage/styles/Register.style.tsx
Labels: Feat, Design

#22 Feature/#3/register
  frontend/src/App.tsx
  frontend/src/pages/LoginPage/components/LoginForm.tsx
  frontend/src/pages/RegisterPage/components/RegisterForm.tsx
  frontend/src/pages/RegisterPage/styles/City.list.ts
  frontend/src/pages/RegisterPage/styles/Register.style.tsx
  frontend/src/style/GlobalStyle.ts
  frontend/src/style/MobileStyle.ts
Labels: Feat, Design

#24 [Design 🎨] AI일정(2) UI
  frontend/src/components/BackButton/BackButton.tsx
  frontend/src/components/BackButton/styles/BackButton.style.tsx
  frontend/src/pages/AISchedule2Page/AISchedule2.tsx
  frontend/src/pages/AISchedule2Page/styles/AISchedule2.style.tsx
  frontend/src/router.tsx
Labels: Design

#25 [Feat 💡] 회원가입 기능 1차
  frontend/.eslintrc.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/prettierrc.json
  frontend/src/api/axiosInstance.ts
  frontend/src/pages/AISchedule1Page/AISchedule1.tsx
  frontend/src/pages/AISchedule1Page/styles/AISchedule1.style.tsx
  frontend/src/pages/AISchedule2Page/AISchedule2.tsx
  frontend/src/pages/LoginPage/Login.tsx
  frontend/src/pages/LoginPage/components/LoginForm.tsx
  frontend/src/pages/RegisterPage/components/RegisterForm.tsx
  frontend/src/router.tsx
  frontend/src/stores/useScheduleStore.ts
Labels: Feat, Design

#28 [Feat 💡] 캘린더 1차
  frontend/src/components/BottomMenuBar/styles/BottomMenuBar.style.tsx
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/CalendarPage/components/MainCalendar.tsx
  frontend/src/pages/CalendarPage/styles/Calendar.style.tsx
  frontend/src/pages/LoginPage/components/CreateAccount.tsx
  frontend/src/pages/LoginPage/styles/Login.style.tsx
Labels: Feat, Design

#29 [Design 🎨] 뒤로 가기 버튼 고정 및 스크롤 영역 지정
  frontend/src/pages/AISchedule1Page/styles/AISchedule1.style.tsx
Labels: fix, Design

#31 Feature/#30/profile
  frontend/public/img/profile-default.png
  frontend/src/api/auth/getList.ts
  frontend/src/api/auth/getMyInfo.ts
  frontend/src/api/profile/postProfileUpdate.ts
  frontend/src/pages/ProfilePage/Profile.tsx
  frontend/src/pages/ProfilePage/components/LogoutButton.tsx
  frontend/src/pages/ProfilePage/components/ProfileSection.tsx
  frontend/src/pages/ProfilePage/styles/Profile.style.tsx
Labels: Feat

#34 [Feat 💡] AI일정(3) 기능
  frontend/src/api/schedule/getSchedule.ts
  frontend/src/pages/AISchedule3Page/AISchedule3.tsx
  frontend/src/pages/AISchedule3Page/components/Schedule.tsx
  frontend/src/pages/AISchedule3Page/styles/AISchedule3.style.tsx
  frontend/src/style/CityColor.ts
  frontend/src/style/MonthColor.ts
Labels: Feat, Design
