Repository AI-iLearning/AI-Learning, pull requests merged in 2024-08, with the labels that each got.

#35 [Feat 💡] 캘린더에 AI 스케줄 일정 반영
  frontend/src/api/calendar/getTimelineAll.ts
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/CalendarPage/components/MainCalendar.tsx
  frontend/src/pages/CalendarPage/styles/Calendar.style.tsx
Labels: Feat, Design

#37 [Feature/#23/calendar] 캘린더 기능 보완
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/CalendarPage/components/DateDrawer.tsx
  frontend/src/pages/CalendarPage/components/MainCalendar.tsx
  frontend/src/pages/CalendarPage/styles/Calendar.style.tsx
Labels: fix, Feat, Design

#38 [Feat 💡] 일별 일정 로드 기능 1차
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/calendar/postTimelineDay.ts
  frontend/src/pages/CalendarPage/components/DateDrawer.tsx
  frontend/src/pages/CalendarPage/components/DrawerButton.tsx
  frontend/src/pages/CalendarPage/components/PlaceBox.tsx
  frontend/src/pages/CalendarPage/styles/Calendar.style.tsx
  frontend/src/pages/CalendarPage/styles/DateDrawer.style.tsx
  frontend/src/pages/CalendarPage/styles/DrawerButton.style.tsx
  frontend/src/pages/CalendarPage/styles/PlaceBox.style.tsx
Labels: Feat, Design

#42 [Design 🎨] 요일 위치 스크롤 바깥 영역으로 뺌
  frontend/src/pages/CalendarInputPage/CalendarInput.tsx
  frontend/src/pages/CalendarInputPage/components/CalendarFrame.tsx
  frontend/src/pages/CalendarInputPage/styles/CalendarFrame.style.tsx
Labels: fix, Design

#44 [Refactoring ⚙️] 하단메뉴바 하나로 관리
  frontend/src/App.tsx
  frontend/src/pages/CalendarPage/Calendar.tsx
  frontend/src/pages/ProfilePage/Profile.tsx
  frontend/src/pages/RankPage/Rank.tsx
  frontend/src/pages/RecommendPage/Recommend.tsx
Labels: Refactor

#47 [Feature/#4/user-status] 전역 상태 관리 초기 설정
  frontend/src/api/auth/getMyInfo.ts
  frontend/src/hooks/useUser.ts
  frontend/src/pages/AISchedule2Page/AISchedule2.tsx
  frontend/src/pages/AISchedule3Page/AISchedule3.tsx
  frontend/src/pages/CalendarPage/components/MainCalendar.tsx
  frontend/src/pages/CalendarPage/components/PlaceBox.tsx
  frontend/src/pages/LoginPage/components/LoginForm.tsx
  frontend/src/pages/ProfilePage/components/LogoutButton.tsx
  frontend/src/pages/ProfilePage/components/ProfileSection.tsx
  frontend/src/stores/authToken.ts
Labels: Feat, Refactor

#49 [Design 🎨] BottomMenuBar 디자인 및 경고 수정
  frontend/public/index.html
  frontend/src/components/BottomMenuBar/BottomMenuBar.tsx
  frontend/src/components/BottomMenuBar/styles/BottomMenuBar.style.tsx
  frontend/src/style/MobileStyle.ts
Labels: fix, Design

#50 [Design 🎨] BottomMenuBar 위치 조정
  frontend/src/components/BottomMenuBar/styles/BottomMenuBar.style.tsx
  frontend/src/pages/CalendarPage/styles/Calendar.style.tsx
  frontend/src/pages/CalendarPage/styles/DateDrawer.style.tsx
Labels: Design

#52 [Fix ✏️] 임시방편 높이 해결
  frontend/src/pages/CalendarPage/styles/Calendar.style.tsx
  frontend/src/style/MobileStyle.ts
Labels: fix

#54 [Design 🎨] height 조정
  frontend/src/pages/CalendarPage/components/MainCalendar.tsx
  frontend/src/pages/CalendarPage/styles/Calendar.style.tsx
  frontend/src/pages/CalendarPage/styles/DateDrawer.style.tsx
Labels: Design

#55 [Design 🎨] height 수정2
  frontend/src/pages/CalendarPage/styles/Calendar.style.tsx
  frontend/src/pages/CalendarPage/styles/DateDrawer.style.tsx
  frontend/src/style/MobileStyle.ts
Labels: Design

#56 [Design 🎨] 하단 버튼 위치 조정
  frontend/src/pages/CalendarInputPage/styles/CalendarFrame.style.tsx
Labels: Design

#57 [Design 🎨] 하단 버튼 수정
  frontend/src/pages/CalendarInputPage/styles/CalendarFrame.style.tsx
Labels: Design

#58 [Design 🎨] 하단 버튼 수정
  frontend/src/pages/CalendarInputPage/styles/CalendarFrame.style.tsx
Labels: Design

#59 [Design 🎨] 하단 버튼 수정
  frontend/src/pages/CalendarInputPage/styles/CalendarFrame.style.tsx
Labels: Design

#60 [Design 🎨] 요일 다시 스크롤 영역 안으로 되돌림
  frontend/src/pages/CalendarInputPage/CalendarInput.tsx
  frontend/src/pages/CalendarInputPage/components/CalendarFrame.tsx
  frontend/src/pages/CalendarInputPage/styles/CalendarFrame.style.tsx
Labels: Design

#61 [Design 🎨] 하단 버튼 안 보이는 문제
  frontend/src/pages/CalendarInputPage/CalendarInput.tsx
  frontend/src/pages/CalendarInputPage/components/CalendarFrame.tsx
  frontend/src/pages/CalendarInputPage/styles/CalendarFrame.style.tsx
  frontend/src/style/MobileStyle.ts
Labels: Design

#65 [Feat💡] AI일정 수정 기능 - 드래그앤드롭
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/schedule/postEdit.ts
  frontend/src/components/BackButton/styles/BackButton.style.tsx
  frontend/src/pages/AISchedule3Page/AISchedule3.tsx
  frontend/src/pages/AISchedule3Page/components/Schedule.tsx
  frontend/src/pages/AISchedule3Page/components/ScheduleItem.tsx
  frontend/src/pages/AISchedule3Page/styles/AISchedule3.style.tsx
  frontend/src/react-device-detect.d.ts
Labels: Feat

#69 [Feature/#36/date drawer] DateDrawer 전반적 기능 구현
  frontend/public/index.html
  frontend/src/api/calendar/getAllPlace.ts
  frontend/src/api/calendar/postTimelineFix.ts
  frontend/src/assets/distance_placeholder.svg
  frontend/src/pages/CalendarPage/components/DateDrawer.tsx
  frontend/src/pages/CalendarPage/components/DrawerButton.tsx
  frontend/src/pages/CalendarPage/components/MemoPopUp.tsx
  frontend/src/pages/CalendarPage/components/PlaceBox.tsx
  frontend/src/pages/CalendarPage/components/PlaceBoxItem.tsx
  frontend/src/pages/CalendarPage/styles/DateDrawer.style.tsx
  frontend/src/pages/CalendarPage/styles/MemoPopUp.style.tsx
  frontend/src/pages/CalendarPage/styles/PlaceBox.style.tsx
  frontend/src/stores/useDayScheduleStore.ts
Labels: Feat, Design, Refactor

#72 [Feature/#66/place detail] 장소 디테일 2차 구현
  frontend/public/index.html
  frontend/src/api/calendar/postLike.ts
  frontend/src/api/calendar/postPlaceLike.ts
  frontend/src/api/profile/getLike.ts
  frontend/src/hooks/useLikeList.ts
  frontend/src/pages/CalendarPage/components/PlaceBoxItem.tsx
  frontend/src/pages/LoginPage/components/LoginForm.tsx
  frontend/src/pages/PlaceDetailPage/PlaceDetail.tsx
  frontend/src/pages/PlaceDetailPage/components/PlaceMap.tsx
  frontend/src/pages/PlaceDetailPage/styles/PlaceDetail.style.tsx
  frontend/src/router.tsx
Labels: Feat, Design, Refactor
